### ISSUE TITLE
Seizure features for brat config

### ISSUE THREAD

**Issue by arronlacey** [arronlacey/Epilepsy-GATE-app#15]
<attribute name="SeizureType" use="required" value="null"></attribute>
      <attribute name="rule" use="required" value="null"></attribute>
      <attribute name="CUI" use="required" value="null"></attribute>
      <attribute name="sinceInteraction" use="required" value="null"></attribute>
      <attribute name="sinceDateDay" use="required" value="null"></attribute>
      <attribute name="sinceDateMonth" use="required" value="null"></attribute>
      <attribute name="sinceDateYear" use="required" value="null"></attribute>
      <attribute name="numPeriodValue" use="required" value="null"></attribute>
      <attribute name="numPeriodLower" use="required" value="null"></attribute>
      <attribute name="numPeriodUpper" use="required" value="null"></attribute>
      <attribute name="sinceperiod" use="required" value="null"></attribute>
      <attribute name="sinceDrug" use="required" value="null"></attribute>

**Comment by huwstrafford** [comment]
I'm unsure of what exactly I am supposed to do with text code above, when I add it into my .conf file, brat no longer recognise it as an .conf file and I can't annotate anything.
Also, should I be matching the names of my entites and attributes to match the ones above?

**Comment by huwstrafford** [comment]
I'm unsure of what exactly I am supposed to do with text code above, when I add it into my .conf file, brat no longer recognise it as an .conf file and I can't annotate anything.
Also, should I be matching the names of my entites and attributes to match the ones above?

**Comment by arronlacey** [comment]
Hi Huw - no need to copy straight in. It's just a guide as to what features (or attributes in brat speak) I am using in Gate. So for example I have an attribute called numPeriodLower which would also need to be an attribute in brat. And same for all the other features in the file I've uploaded (numPeriodHigher, sinceDrug etc....)
