### ISSUE TITLE
Epilepsy CUI lists for Algorithm

### ISSUE THREAD

**Issue by BeataFS** [arronlacey/Epilepsy-GATE-app#19]
Epilepsy type and seizure list are ready for  review. It is hard to incorparate the new ILAE classification as the terms are often missing from the UMLS (2018)   I've created this  separate card as this item got lost in the exchanges under Write brat config (above)  @OwenPickrell
- [ ] to be reviewed

**Comment by OwenPickrell** [comment]
I've looked at epilepsy_clean_V4 and it looks fine. Was that the right file to check?

**Comment by BeataFS** [comment]
The  final version is epilepsy.lst ,it is slightly different to the one that you had looked  at (I thought I had removed it last Thursday) . 
This one  and the seizure _clean.lst are  in BeataFS/ExECT-BRAT

**Comment by arronlacey** [comment]
Would be good to get epilepsy.lst version controlled Beata rather than hardcoded _v4 etc. How you getting on with that?

**Comment by BeataFS** [comment]
They are done. epilepsy.lst and seizure_clean.lst are in github BeataFS ExECT--BRAT. Owen must've pulled v4 before I updated it .

Also I couldn't add him to the board in the main ExECT to grab his attention that the lists were ready for review  - that's why I added my own board and allocated the item to him this morning.




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arronlacey** [comment]
Ok great - as long as epilepsy.lst is version controlled you can remove any versions named as _vsomething.

**Comment by BeataFS** [comment]
All done I think

**Comment by OwenPickrell** [comment]
Ok - I've added a look and tweaked a bit, looks good

**Comment by BeataFS** [comment]
Sorry can't see the changes . Owen, have you saved the changes to the files before pushing?  Can't open the .DS_Store either

**Comment by arronlacey** [comment]
Changed title to reflect that CUI lists are to be used on the algorithm side of things as we are using Sam's functionality to collect CUIs and terms rather than hardcoding
