### ISSUE TITLE
Febrile seizures

### ISSUE THREAD

**Issue by arronlacey** [arronlacey/Epilepsy-GATE-app#23]

**Comment by BeataFS** [comment]
In  markup  this is annotated as History  : Personal history ( febrile seizures,  head inj, birth inj - which are mentioned  )  and Family history  of epilepsy . There could be an overlap here with comorbidities e.g. learning disability

**Comment by BeataFS** [comment]
I have now created a gazetteers for commodities and  it would feed to the rules for other diagnosis and history, which would have things like febrile seizures, learning disabilities, and non-epileptic attacks.
