### ISSUE TITLE
Markup 40 epilepsy letters and test ExEct

### ISSUE THREAD

**Issue by OwenPickrell** [arronlacey/Epilepsy-GATE-app#29]

**Comment by OwenPickrell** [comment]
Make a note of any probs, discuss by skype at 12pm 25/6/19

**Comment by BeataFS** [comment]
As a result of testing markup we started modifying ExECT -  lists and rules.  I think we need to add quite a bit to the lists (Lookups which are derived from the UMLS terms)  to cover history, epilepsy cause, comorbidities.
? of concepts : ExECT output extracted diagnosis and from this we "manually" identified Epilepsy, seizure type, and epilepsy from seizure" our Markup config produced Diagnosis , Seizure type, and also seizure frequency which has seizure related CUI as a feature.   Do we want to keep all the diagnostic concepts together?

**Comment by BeataFS** [comment]
Please see my comment above @arronlacey1 @OwenPickrell @huwstrafford

**Comment by arronlacey** [comment]
Ok great. Yes any changes to align with markup should be done. I think taking the same kind of approach with MS comorbidities and symptoms. Have little .lst files i.e for symptomatic causation and add to the epilepsy.def file with an appropriate Major/Minor type and Annotaion name.

**Comment by BeataFS** [comment]
So we'll need to redo the config for ExECT... Would the output then be a mix of concepts and features?
