### ISSUE TITLE
Write brat config

### ISSUE THREAD

**Issue by arronlacey** [arronlacey/Epilepsy-GATE-app#3]

**Comment by BeataFS** [comment]
Create drop-down lists with epilepsy  and seizure type CUIs  to add to the config file.  I suppose we need the same for medication (?)  and epilepsy cause.

**Comment by arronlacey** [comment]
Hopefully Sam's algorithm will get the appropriate drop down list from the text that's been highlighted

**Comment by BeataFS** [comment]
For the medication it would probably work (name only) but for the epilepsy types and seizure types, and cause we may not have enough annotated examples. We could do both and compare .

**Comment by BeataFS** [comment]
Created a list of epilepsy  typs + CUIs  - to be agreed  on  06/03/2019
