### ISSUE TITLE
Clean ExECT Annotations for MedGATE

### ISSUE THREAD

**Issue by arronlacey** [arronlacey/Epilepsy-GATE-app#7]

**Comment by BeataFS** [comment]
Need to review epilepsy  CUIs as some events and diagnosis are not being  picked up -  important for  the onset and cause  annotations.

**Comment by arronlacey** [comment]
Ok good stuff. Is Owen needed for this as well?

**Comment by arronlacey** [comment]
Ok good stuff. Is Owen needed for this as well?

**Comment by arronlacey** [comment]
Ok good stuff. Is Owen needed for this as well?

**Comment by BeataFS** [comment]
Not really
